wallpaper {
    monitor =
    path = ~/Pictures/Wallpapers/archy-plain.png
    fit_mode = cover
}

wallpaper {
    monitor =
    path = ~/Pictures/Wallpapers/archy-btw.png
    fit_mode = cover
}

wallpaper {
    monitor =
    path = ~/Pictures/Wallpapers/archy-stylish.jpg
    fit_mode = cover
}

wallpaper {
    monitor =
    path = ~/Pictures/Wallpapers/archy-xorg.jpg
    fit_mode = cover
}

wallpaper {
    monitor =
    path = ~/Pictures/Wallpapers/archy.rainbow.png
    fit_mode = cover
}
